### ISSUE TITLE
current build claims to be 1.1release, but the resultant app says it is 1.1beta

### ISSUE THREAD

**Issue by relaystar** [linuxserver/docker-booksonic#13]
I've installed the latest image from dockerhub using the provided instructions.  The result looks correct:
```
# docker inspect -f '{{ index .Config.Labels "build_version" }}' booksonic
Linuxserver.io version:- 1.1.Release-ls23 Build-date:- 2019-06-27T05:45:22+00:00
```

However once running the web app declares itself to be the beta release:

```
Version | 1.1.beta1 – June 27, 2019

```
and querying the API (ping.view) returns this:
```
{
   "subsonic-response" : {
      "status" : "ok",
      "version" : "1.14.0",
      "booksonic" : "outdated_beta"
  }
}
```

**Comment by tobbenb** [comment]
I have looked at the code and build logs, and we are indeed checking out 1.1release when building. If you go here [https://github.com/popeen/Popeens-Subsonic/releases](https://github.com/popeen/Popeens-Subsonic/releases) you can see that the commit is a043e59 for 1.1release, and that is also the version we build.

Full log [here](https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-booksonic/job/master/61/consoleFull)
If you click on the 2 commits to master since this release on the Releases page, you can see that the version was changed after the release was made. This is most likely the reason why it looks like we are building the wrong version.


```[0m[91mNote: checking out '1.1.Release'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a043e59 Fixed incorrect path in a couple of test cases

**Comment by relaystar** [comment]
OK, I see that the tagging in the source repo is wrong, as you allude to.  The version tagged as 1.1release isn't actually 1.1release.  I've created an issue with the author:

https://github.com/popeen/Popeens-Subsonic/issues/44

**Comment by nelsonblaha** [comment]
Could this also be causing the `A new version is available. Download Booksonic 1.1 here.` in the sidebar that I see?

**Comment by tobbenb** [comment]
Yes

**Comment by CHBMB** [comment]
I think this has been resolved now.  Version in webui shows `1.1 – April 28, 2019`
